alias ll='ls -l'
alias la='ls -a'
alias l='ls -CF'
alias h='history'
alias r='rake'
alias go="cd ~/git"
alias dots="cd ~/git/dotsfiles"
alias rgrep="grep -r"
alias ffp='/Applications/Firefox.app/Contents/MacOS/firefox-bin -profilemanager'

alias less='less -XLR'

# SO META
alias realias='. ~/.bash_aliases'
alias rebash='. ~/.bashrc'

# git
alias gs='git s'
alias gd='git d'
alias ga='git add'
alias gco='git co'
alias gb='git b'
alias gdx='git diff | ~/Downloads/GitX.app/Contents/Resources/gitx'

function git_current_branch() {
  git symbolic-ref HEAD 2> /dev/null | sed -e 's/refs\/heads\///'
}

alias gpthis='git push origin HEAD:$(git_current_branch)'
alias grb='git rebase -p'
alias gup='git fetch origin && grb origin/$(git_current_branch)'
alias gm='git merge --no-ff'
alias disk='du -d 1 -h'
alias h='heroku'

[[ -e ~/.bash_aliases.local ]] && . ~/.bash_aliases.local
