alias ll='ls -l'
alias la='ls -a'
alias l='ls -CF'
alias tree='tree -C'
alias h='history'
alias r='rake'
alias dots="cd ~/git/dotsfiles"
alias rgrep="grep -r"
alias ffp='/Applications/Firefox.app/Contents/MacOS/firefox-bin -profilemanager'

alias less='less -XLR'

# SO META
alias realias='. ~/.bash_aliases'
alias rebash='. ~/.bashrc'

# git
alias gs='git s'
alias gf='git fetch'
alias gd='git d'
alias ga='git add'
alias gco='git co'
alias gb='git b'
alias gdh='git diff HEAD'
alias gsh='git show HEAD'
alias gdx='git diff | ~/Downloads/GitX.app/Contents/Resources/gitx'
alias reup='git fetch && git pull origin master'

#alias pryr="pry -r ./config/environment -r rails/console/app -r rails/console/helpers"

# RHEL Aliases
if [ -f /etc/redhat-release ]; then
  alias ls='ls --color=auto'
fi
if [ -f /etc/issue ]; then
  alias ls='ls --color=auto'
fi


function git_current_branch() {
  git symbolic-ref HEAD 2> /dev/null | sed -e 's/refs\/heads\///'
}

alias gpthis='git push origin HEAD:$(git_current_branch)'
alias grb='git rebase -p'
alias gup='git fetch origin && grb origin/$(git_current_branch)'
alias gm='git merge --no-ff'
alias disk='du -d 1 -h'

# Heroku
alias h='heroku'
alias hlogs='heroku logs -t --app'

# Bundler
alias bi='bundle install --binstubs=./.bin'
alias brake='bundle exec rake'
alias bx='bundle exec'

# tmux
alias mux='tmux -f ~/tmux.conf'

# OSX
alias screensaver='/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine'
alias ss='/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine'

alias crontab='VIM_CRONTAB=true crontab'

[[ -e ~/.bash_aliases.local ]] && . ~/.bash_aliases.local

mwiki() { dig +short txt "$*".wp.dg.cx; }

alias rtest='ruby -I"lib:test"'

alias reup='git fetch; git merge origin/master'

alias keys='ssh-add ~/.ssh/id_dsa; ssh-add ~/.ssh/umsondo'
