#!/bin/bash

# rvm
if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
  . "$HOME/.rvm/scripts/rvm"
  # Favor Brew
  export PATH="~/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:$PATH"
  #export PATH="$HOME/.rvm/rubies/ruby-1.8.7-p299/bin:/usr/local/bin:/opt/local/lib/postgresql84/bin:/usr/local/bin:/usr/local:$PATH"
elif [[ -s "/etc/profile.d/rvm.sh" ]]; then
  . "/etc/profile.d/rvm.sh"
fi

# NVM
export NVM_DIR="$HOME/.nvm"
if [[ -f "/usr/local/opt/nvm/nvm.sh" ]]; then
. "/usr/local/opt/nvm/nvm.sh"
fi

# History
export HISTCONTROL=erasedups:ignoredups
export HISTSIZE=10000
export HISTIGNORE="&:ls:[bf]g:exit"
export PROMPT_COMMAND="history -a"
shopt -s histappend
shopt -s cmdhist

# Enable git completion and handy functions like __git_ps1
if [[ -f "/usr/local/etc/bash_completion.d/git-completion.bash" ]]; then
  . "/usr/local/etc/bash_completion.d/git-completion.bash"
fi

if [[ -f "/usr/local/etc/bash_completion.d/git-prompt.sh" ]]; then
  . "/usr/local/etc/bash_completion.d/git-prompt.sh"
  export PS1="[\h:\w\$(__git_ps1)] \u$ "
fi

[[ -s "/etc/bash_completion.d/git" ]] && . "/etc/bash_completion.d/git"
[[ -s "$HOME/.bashrc" ]] && . "$HOME/.bashrc"

# Completions
complete -C ~/.bash/completion/rake_completion -o default rake
complete -C ~/.bash/completion/project_completion -o default c

# Prompt
export LANG=en_US.UTF-8

# Personal executables
export PATH=$HOME/bin:$PATH

# Bundler
export PATH="./.bin:$PATH"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

[[ -f /usr/libexec/java_home ]] && export JAVA_HOME="$(/usr/libexec/java_home)"

# AWS
export AWS_IAM_HOME="/usr/local/opt/aws-iam-tools/jars"
export AWS_CREDENTIAL_FILE=$HOME/.aws-credentials-master
