if has("gui")
  set go=-T " Remove toolbar
  set go+=c
  set gfn=Monaco:h14
  set visualbell
  
  if &background == "dark"
    hi normal guibg=black
  endif
  
  colors koehler
  
  set mousehide " Hide the mouse when typing text
  
  " Include user's local vim config
  if filereadable(expand("~/.gvimrc.local"))
    source ~/.gvimrc.local
  endif
endif
