""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Pathogen needs to be setup first
"
filetype off
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Basic Setup

" Colors
syntax on
colors inkpot
"set term=xterm-color
set t_Co=256
set bg=dark

"call pathogen#runtime_append_all_bundles()

filetype plugin indent on " Enable filetype-specific indenting and plugins
set backspace=indent,eol,start
set nocompatible
set sw=2 sts=2 et ai
set whichwrap=b,s,h,l
set wildmenu
set wildmode=list:longest
set list listchars=tab:\ \ ,trail:·
set nostartofline " restart at last cursor position - YAY!
set scrolloff=10  " keep 10 lines above and below position
set showcmd
set showmatch
set ruler

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

set cpoptions+=n
set showbreak=↳\\

" File name, git branch, and line & col position
set laststatus=2
set statusline=%F\ <%{GitBranch()}>\ %l,%v

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Key Mappings
"
let mapleader = ","

" Opens a tab edit command with the path of the currently edited file filled in
noremap <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

" Opens a tab edit command with the path of the currently edited file filled in
" Normal mode: <Leader>t
noremap <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>

noremap <Leader>r :!ruby %<CR>
noremap <Leader>w :w!<CR>
noremap <Leader>x :x!<CR>
noremap <Leader>q :qa<CR>
noremap <Leader>ra :!rake %<CR>
noremap <Leader>, :!!<CR>
noremap <Leader>c <C-w>c<CR>
"noremap <Leader>a :<Leader>A<CR>
noremap <leader>s :set list!<CR>
noremap <leader>m :!markdown < %:p > /tmp/`basename %`.html; open file:///tmp/`basename %`.html<CR>
noremap <leader>g :FuzzyFinderFile<CR>
map <F5> :%s/<\([^>]\)*>/\r&\r/g<enter>:g/^$/d<enter>vat=
map <F8> vatJxvito<right><left>x
map <F7> /\v^\s*([a-zA-Z\-0-9\$])<enter>qm<F6>nq@q1000@@:1<enter>

"noremap ,c :!cucumber --format pretty %<CR>
" Run the cucumber scenario under the cursor <3
noremap <Leader>f :execute "!bundle exec cucumber --format pretty %:".line('.')<CR>

" NERd Tree
noremap <Leader>t :execute 'NERDTreeToggle'<CR> 
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p

" Dict - scrumtrilescent!
noremap <Leader>d :execute "!dict <cword>"<CR>

" Source this file
noremap <Leader>v :source ~/.vimrc<CR>

" Map ctrl-j to escape for more home row action!
:imap <C-j> <Esc>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Filetypes - Move Me
" Load matchit (% to bounce from do to end, etc.)
runtime! macros/matchit.vim

augroup myfiletypes
  " Clear old autocmds in group
  autocmd!
  " autoindent with two spaces, always expand tabs
  autocmd FileType rspec,ruby,eruby,yaml,rake set ai sw=2 sts=2 et
augroup END

" ruby
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1

"clojure"
let vimclojure#HighlightBuiltins = 1
let vimclojure#ParenRainbow = 1

" change to the working directory of open buffer unless in /tmp
"autocmd BufEnter * if expand("%:p:h") !~ '^/tmp' | lcd %:p:h | endif

"improve autocomplete menu color
highlight Pmenu ctermbg=238 gui=bold
augroup mkd
  autocmd BufRead *.mkd,*.md  set ai formatoptions=tcroqn2 comments=n:&gt;
augroup END

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" History
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp

if $VIM_CRONTAB == "true"
  set nobackup
  set nowritebackup
endif

" Marks
set viminfo='100,f1

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Folding
set foldenable
set foldmethod=syntax
set foldlevel=100
au BufWinLeave * silent! mkview " Automatically load/save folding views
au BufWinEnter * silent! loadview

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Misc 
"
" Highlight > 80 cols
" http://stackoverflow.com/questions/235439/vim-80-column-layout-concerns
"if has("colorcolumn")
"  set colorcolumn=80
"else
"  au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
"endif

" gist-vim
let g:gist_clip_command = 'pbcopy'
let g:gist_detect_filetype = 1
let g:gist_open_browser_after_post = 1
let g:SuperTabDefaultCompletionType = "context"

" Include user's local vim config
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif

if has("gui")
  set go=-T " Remove toolbar
  set go+=c
  set gfn=Monaco:h12
  set visualbell

  if &background == "dark"
    hi normal guibg=black
  endif

  colors koehler

  set mousehide " Hide the mouse when typing text

  " Include user's local vim config
  if filereadable(expand("~/.gvimrc.local"))
    source ~/.gvimrc.local
  endif
endif
